server:
  port: 8080  # 设置后端服务监听端口为8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usst_ads  # 数据库连接URL，使用本地MySQL数据库
    username: root  # 数据库用户名
    password: root  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 使用的数据库驱动

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 配置路径匹配策略

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml  # MyBatis的Mapper文件位置
  type-aliases-package: org.example.backend.entity  # 配置实体类扫描路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启MyBatis日志输出
